language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
deploy:
  provider: npm
  email: eevert.saukkokoski@appgyver.com
  api_key:
    secure: Ob3FZO+u9OHQ3SjJRDO17VucE232Odl3VsIOAXCDFdTMwMCS1rlGkYR0aJgD7X8zl1EPCyuXX3mFS3CA0DmvGB3UWUISh8w3nQxWgtHnQfCNOxVw6xnRvU5AMxH351fCJpDH3afz1dzlKTghNUMLkoSwJ+gcUO1ZjSbeVPWViVs=
  on:
    tags: true
    all_branches: true
    repo: AppGyver/ag-types
